- hosts: lampstack
  become: true
  become_method: sudo
  become_user: root

  vars:
    php_enable_php_fpm: true
    apache_vhosts:
      - servername: "hostla.suburbanau.com"
        documentroot: "/var/www/hostla.suburbanau.com"
        extra_parameters: |
              ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/example"

  roles:
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.apache-php-fpm
    - geerlingguy.mysql 
